namespace Opinionated.DotNet.CodingStandards.Tests;

[RuleDoc("IDE0001", "Simplify name",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0001",
    Untestable = "IDE0001 (SimplifyNames) is registered with EnforceOnBuild.Never in Roslyn's EnforceOnBuildValues.cs (`public const EnforceOnBuild SimplifyNames = /*IDE0001*/ EnforceOnBuild.Never;`, preceded by the comment \"TODO: Allow enforcing simplify names and related diagnostics on build once we validate their performance charactericstics.\"). The EnforceOnBuild enum documents Never as \"an IDE-only diagnostic that cannot be enforced on build\", so the descriptor is excluded from the command-line/build analyzer set and IDE0001 never appears in MSBuild SARIF output - even though this package sets dotnet_diagnostic.IDE0001.severity = warning, EnforceCodeStyleInBuild=true, and TreatWarningsAsErrors=true. Confirmed by dotnet/roslyn issue #77120 (which names IDE0001 and IDE0049 as affected) and by the same EnforceOnBuild.Never gating IDE0002/IDE0003. Source: src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs and EnforceOnBuild.cs (dotnet/roslyn).")]
[RuleDoc("IDE0002", "Simplify member access",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0002",
    Untestable = "IDE0002's analyzer (SimplifyTypeNamesDiagnosticAnalyzerBase, Roslyn) builds its descriptor as CreateDescriptorWithId(IDEDiagnosticIds.SimplifyMemberAccessDiagnosticId, EnforceOnBuildValues.SimplifyMemberAccess, ..., isUnnecessary: true), and EnforceOnBuildValues.SimplifyMemberAccess == EnforceOnBuild.Never (Source: src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs). EnforceOnBuild.Never is documented as \"an IDE-only diagnostic that cannot be enforced on build\" (Source: src/Analyzers/Core/Analyzers/EnforceOnBuild.cs) and stamps the \"EnforceOnBuild_Never\" custom tag onto the descriptor (Source: src/Analyzers/Core/Analyzers/DiagnosticCustomTags.cs). The command-line/MSBuild analyzer host honours that tag and excludes IDE0002 from build SARIF regardless of dotnet_diagnostic.IDE0002.severity or EnforceCodeStyleInBuild=true, so no code pattern can make HasError(\"IDE0002\") true in this build-output harness. Empirically confirmed: a genuine `return Program.Value();` violation reported by `dotnet format style --diagnostics IDE0002` produced NO IDE0002 in the dotnet build SARIF even at severity=error + EnforceCodeStyleInBuild=true, while a control IDE0004 (EnforceOnBuild.WhenExplicitlyEnabled) DID surface in the same build. Note IDE0002 is isConfigurable:true (severity-configurable), so the gate is the EnforceOnBuild_Never tag, not NotConfigurable. Source: src/Analyzers/Core/Analyzers/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs.")]
[RuleDoc("IDE0003", "Remove this or Me qualification",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0003",
    Untestable = "IDE0003's analyzer (AbstractSimplifyThisOrMeDiagnosticAnalyzer, src/Features/Core/Portable/SimplifyThisOrMe/AbstractSimplifyThisOrMeDiagnosticAnalyzer.cs) is constructed with EnforceOnBuildValues.RemoveQualification, which is hardcoded to EnforceOnBuild.Never (`public const EnforceOnBuild RemoveQualification = /*IDE0003*/ EnforceOnBuild.Never;` in src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs). The EnforceOnBuild.Never member is documented as \"an IDE-only diagnostic that cannot be enforced on build\" (src/Analyzers/Core/Analyzers/EnforceOnBuild.cs), and DiagnosticCustomTags.Create stamps such descriptors with WellKnownDiagnosticTags.NotConfigurable (src/Analyzers/Core/Analyzers/DiagnosticCustomTags.cs: `Debug.Assert(isConfigurable || enforceOnBuild == EnforceOnBuild.Never)`). Consequently IDE0003 never runs during command-line build and cannot be turned on via editorconfig severity or EnforceCodeStyleInBuild=true. Empirically confirmed: a probe of `this._value` field qualification with EnforceCodeStyleInBuild=true and NoWarn=IDE0055 produced a clean build (0 warnings/0 errors) and an EMPTY SARIF - no IDE0003 at note/warning/error and no IDE0055 substitute (so it is NOT merely formatter-backed). Tracked upstream as dotnet/roslyn#77120.")]
[RuleDoc("IDE0038", "Use pattern matching to avoid is check followed by a cast",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0038",
    Untestable = "IDE0038's analyzer, CSharpIsAndCastCheckWithoutNameDiagnosticAnalyzer, ships only in the IDE-only Features assembly (Microsoft.CodeAnalysis.CSharp.Features) at src/Features/CSharp/Portable/UsePatternMatching/CSharpIsAndCastCheckWithoutNameDiagnosticAnalyzer.cs, NOT in the build-time Microsoft.CodeAnalysis.CSharp.CodeStyle package; that assembly is not loaded during 'dotnet build', so IDE0038 is never reported. Only the sibling IDE0020 analyzer (CSharpIsAndCastCheckDiagnosticAnalyzer, src/Analyzers/CSharp/Analyzers/UsePatternMatching/) runs at build, and it reports ONLY IDEDiagnosticIds.InlineIsTypeCheckId (IDE0020) because its TryGetPatternPieces requires a LocalDeclarationStatementSyntax (the 'var v = (Type)x;' saved-to-local shape). Verified empirically: building the canonical without-variable violation 'if (obj is int) { if ((int)obj == 1) { ... } }' in the harness with dotnet_diagnostic.IDE0038.severity=error forced via .editorconfig produced ZERO diagnostics. The EnforceOnBuildValues.InlineIsTypeWithoutName=Recommended value is moot because the reporting analyzer is absent at build. Source: src/Features/CSharp/Portable/UsePatternMatching/CSharpIsAndCastCheckWithoutNameDiagnosticAnalyzer.cs (dotnet/roslyn).")]
[RuleDoc("IDE0084", "Use pattern matching (IsNot operator)",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0084",
    Untestable = "IDE0084's analyzer (VisualBasicUseIsNotExpressionDiagnosticAnalyzer in src/Analyzers/VisualBasic/Analyzers/UseIsNotExpression/VisualBasicUseIsNotDiagnosticAnalyzer.vb) is declared `<DiagnosticAnalyzer(LanguageNames.VisualBasic)>` and registers context.RegisterSyntaxNodeAction(AddressOf SyntaxNodeAction, SyntaxKind.NotExpression) on the VB-only `Not x Is y` expression, reporting IDEDiagnosticIds.UseIsNotExpressionDiagnosticId (\"IDE0084\"). Because the attribute scopes the analyzer to VisualBasic only, Roslyn never instantiates it for a C# compilation, so it cannot run against the harness's net10.0 C# project. A gh api code search of dotnet/roslyn for UseIsNotExpressionDiagnosticId returns only the Core ID constant (src/Analyzers/Core/Analyzers/IDEDiagnosticIds.cs) and VisualBasic-tree files - there is no C# analyzer that emits IDE0084, and the C# `is not` operator is an unrelated compiler-native construct handled by CSharpUseNotPatternDiagnosticAnalyzer which reports the DISTINCT id IDE0083 (UseNotPatternDiagnosticId), not IDE0084. No PackageReference, NoWarn, LangVersion pin, or target-framework switch can convert the single C#-only project into a VB compilation, so the rule can never fire in this harness. Source: src/Analyzers/VisualBasic/Analyzers/UseIsNotExpression/VisualBasicUseIsNotDiagnosticAnalyzer.vb.")]
[RuleDoc("CA1047", "Do not declare protected member in sealed type",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1047",
    Untestable = "CA1047's analyzer (DoNotDeclareProtectedMembersInSealedTypes, Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines) is attributed [DiagnosticAnalyzer(LanguageNames.VisualBasic)] only (the class comment states \"This rule is not implemented for C# as the compiler warning CS0628 already covers this part\"). Roslyn's build host loads packaged analyzers through AnalyzerFileReference, whose GetExtensions(language)/GetAnalyzerTypeNameMap path returns no analyzer types for a language not declared in the [DiagnosticAnalyzer] attribute, so the analyzer is never instantiated for the harness's C# (net10.0) compilation and CA1047 cannot appear in SARIF. (CS0628 is only a level-4 compiler warning, not an error, so it is not what preempts the rule - the VB-only language registration is the structural gate.) Verified empirically: a sealed class declaring a protected field, protected method, and protected property (CS0628 suppressed via NoWarn) built against the packed package surfaced CA1051/SA1649/IDE0055 but had ZERO CA1047 occurrences in SARIF, and a metadata read of the shipped Microsoft.CodeAnalysis.NetAnalyzers.dll v10.0.102 shows the DiagnosticAnalyzer attribute on this type carries only the language string \"Visual Basic\". The dotnet/sdk unit test's C# case passes only because Microsoft.CodeAnalysis.Testing injects the analyzer instance directly into CompilationWithAnalyzers, bypassing the language filter; the package-based build harness cannot do this and has no VB-project path. Source: src/Microsoft.CodeAnalysis.NetAnalyzers/.../ApiDesignGuidelines/DoNotDeclareProtectedMembersInSealedTypes.cs (dotnet/roslyn-analyzers) and AnalyzerFileReference.cs (dotnet/roslyn).")]
[RuleDoc("CA2218", "Override GetHashCode on overriding Equals",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2218",
    Untestable = "CA2218's only analyzer is BasicOverrideGetHashCodeOnOverridingEqualsAnalyzer, decorated `<DiagnosticAnalyzer(LanguageNames.VisualBasic)>` and therefore registered ONLY for Visual Basic compilations; its RegisterSymbolAction (SymbolKind.NamedType, reporting when type.OverridesEquals() AndAlso Not type.OverridesGetHashCode()) never runs on the harness's net10.0 C# project. There is no Core or C# analyzer for CA2218 - the only C# artifact is CSharpOverrideGetHashCodeOnOverridingEquals.Fixer.cs, a code-fix provider that emits no build/SARIF diagnostic. The analyzer's own source remarks state \"CA2218 is not applied to C# since it already reports CS0569.\" (Note: the prior repo reason blaming CS0659 preemption is inaccurate - CS0659 is only a warning and suppressing it does not unblock CA2218; the structural gate is the VB-only analyzer registration.) CA2218 is thus a VB.NET-only rule that structurally cannot fire in a C# build harness. Source: src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicOverrideGetHashCodeOnOverridingEquals.vb (dotnet/roslyn-analyzers).")]
[RuleDoc("CA2224", "Override Equals on overloading operator equals",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2224",
    Untestable = "CA2224's only analyzer is BasicOverrideEqualsOnOverloadingOperatorEqualsAnalyzer (Microsoft.CodeQuality.Analyzers, src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicOverrideEqualsOnOverloadingOperatorEquals.vb), declared <DiagnosticAnalyzer(LanguageNames.VisualBasic)>; it RegisterSymbolAction(SymbolKind.NamedType) and reports CA2224 only for a VB compilation. There is NO C# or language-agnostic analyzer for this rule (the C# side ships only CSharpOverrideEqualsOnOverloadingOperatorEquals.Fixer.cs, a code fixer), so the analyzer registers no actions in this C#-only harness. Verified empirically on net10.0: a class with operator== and no Equals override never emits CA2224 even with <NoWarn>CS0660;CS0661</NoWarn> and AnalysisMode=All; only CA1046/CA2225 surface. Independently, in C# the compiler emits CS0660/CS0661 for that pattern, which TreatWarningsAsErrors promotes to build errors. Permanently untestable in a C#-only build harness. Source: dotnet/roslyn-analyzers (branch main), BasicOverrideEqualsOnOverloadingOperatorEquals.vb.")]
[RuleDoc("CA2226", "Operators should have symmetrical overloads",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2226",
    Untestable = "CA2226's analyzer (OperatorsShouldHaveSymmetricalOverloadsAnalyzer, Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines) registers a SymbolKind.NamedType action and reports only when a user-defined binary operator (IsUserDefinedOperator() && GetParameters().Length==2) from a pair (==/!=, </>, <=/>=) lacks a same-parameter-type counterpart (HasSymmetricOperator -> HasSameParameterTypes, matched per-index via ITypeSymbol.Equals); its descriptor is declared RuleLevel.CandidateForRemoval with the in-source comment \"// C# compiler reports an error\". In C#, defining only one operator of any such pair is itself compile error CS0216 (\"The operator ... requires a matching operator ... to also be defined\"), which the compiler emits per operator BY SIGNATURE over the identical three pairs, failing the build before the analyzer diagnostic can reach SARIF. The compiler's signature-level matching is at least as strict as the analyzer's: it closes every escape hatch, including the asymmetric-parameter case the analyzer's own CSharpTestOperatorTypeAsync unit test covers (operator==(A,int)+operator!=(A,string), still marked {|CS0216:...|}), an orphan added to an otherwise-complete pair, relational sets, and nullable type-identity (int vs int?) edges. CS0216 is a hard ERROR, not a warning: both #pragma warning disable CS0216 and <NoWarn>CS0216 leave it firing (0 Warnings, 2 Errors), so the build never reaches SARIF emission. The three analyzer-checked pairs are an exact subset of the compiler's CS0216-enforced set, so no C# shape exists where CA2226 fires but CS0216 does not. Empirically confirmed on net10.0 (SDK 10.0.101, EnableNETAnalyzers + AnalysisLevel=latest-all + AnalysisMode=All + TreatWarningsAsErrors + ErrorLog SARIF): every paired-operator shape produced \"error CS0216\" and Build FAILED with no CA2226 in output. The rule is a ported-FxCop VB.NET fallback for languages lacking compiler-level operator-symmetry enforcement and is structurally unreachable in C# (same gate class as the repo's CA1047/CS0628 and CA2218/CS0659 entries). Source: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorsShouldHaveSymmetricalOverloads.cs (release/9.0.3xx).")]
[RuleDoc("CA2258", "Providing a 'DynamicInterfaceCastableImplementation' interface in Visual Basic is unsupported",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2258",
    Untestable = "CA2258's analyzer (DynamicInterfaceCastableImplementationAnalyzer, Microsoft.NetCore.Analyzers.InteropServices) reports the diagnostic (DynamicInterfaceCastableImplementationUnsupportedRuleId = \"CA2258\") only inside `if (context.Compilation.Language == LanguageNames.VisualBasic) { context.ReportDiagnostic(...); return; }` within AnalyzeType; the C# code path never reaches that report (it continues to CA2256/CA2257 only). The test harness is C#-only — ProjectBuilder.AddCsprojFile always emits a Microsoft.NET.Sdk C# test.csproj and AddFile writes C# source — so context.Compilation.Language is always LanguageNames.CSharp and the VisualBasic branch is unreachable. There is no C# analogue diagnostic for the same DynamicInterfaceCastableImplementationAttribute misuse, so no indirect workaround exists. Source: src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/DynamicInterfaceCastableImplementation.cs (dotnet/roslyn-analyzers).")]
[RuleDoc("CA2321", "Do not deserialize with JavaScriptSerializer using a SimpleTypeResolver",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2321",
    Untestable = "CA2321's analyzer (DoNotUseInsecureDeserializerJavaScriptSerializerWithSimpleTypeResolver, Microsoft.NetCore.Analyzers.Security) registers its OperationKind.Invocation action inside a RegisterCompilationStartAction that returns early unless WellKnownTypeProvider.TryGetOrCreateTypeByMetadataName resolves all three of System.Web.Script.Serialization.JavaScriptSerializer, .JavaScriptTypeResolver, and .SimpleTypeResolver (WellKnownTypeNames.SystemWebScriptSerialization*). Those types live only in System.Web.Extensions.dll on .NET Framework (Applies-to monikers netframework-3.5..4.8.1; no .NET Core/.NET 5+/.NET Standard moniker) and were removed from .NET Core; on net10.0 they do not exist in any BCL or addable NuGet package, so the gate fails, no actions register, and source referencing the type would not even compile (CS0234). Source: src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/DoNotUseInsecureDeserializerJavascriptSerializerWithSimpleTypeResolver.cs.")]
[RuleDoc("CA5382", "Use Secure Cookies In ASP.NET Core",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca5382",
    Untestable = "Fires when IResponseCookies.Append is called without setting Secure = true in the CookieOptions; requires Microsoft.AspNetCore.Http which is not included in the simple build harness")]
[RuleDoc("CA5383", "Ensure Use Secure Cookies In ASP.NET Core",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca5383",
    Untestable = "Data-flow/taint analysis variant of CA5382 that tracks CookieOptions through variables; same ASP.NET Core dependency and taint-analysis constraint as CA5382")]
[RuleDoc("CA5391", "Use antiforgery tokens in ASP.NET Core MVC controllers",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca5391",
    Untestable = "Fires when ASP.NET Core MVC controller action methods lack antiforgery token validation attributes; requires Microsoft.AspNetCore.Mvc which is not included in the simple build harness")]
[RuleDoc("CA5395", "Miss HttpVerb attribute for action methods",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca5395",
    Untestable = "Fires when ASP.NET MVC controller action methods lack an HTTP verb attribute ([HttpGet], [HttpPost], etc.); requires System.Web.Mvc or Microsoft.AspNetCore.Mvc which are not included in the simple build harness")]
[RuleDoc("CA5396", "Set HttpOnly to true for HttpCookie",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca5396",
    Untestable = "Fires when System.Web.HttpCookie.HttpOnly is set to false or not set; System.Web is not available in .NET Core/5+")]
[RuleDoc("CA5404", "Do not disable token validation checks",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca5404",
    Untestable = "Fires when Microsoft.IdentityModel.Tokens.TokenValidationParameters has validation checks disabled (ValidateAudience=false, ValidateIssuer=false, etc.); Microsoft.IdentityModel.Tokens is not included in the simple build harness")]
[RuleDoc("CA5405", "Do not always skip token validation in delegates",
    HelpLink = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca5405",
    Untestable = "Fires when Microsoft.IdentityModel.Tokens validation delegates (AudienceValidator, IssuerValidator, etc.) always return true without checking; requires Microsoft.IdentityModel.Tokens package not included in the simple build harness")]
[RuleDoc("EnableGenerateDocumentationFile", "Set MSBuild property 'GenerateDocumentationFile' to 'true'",
    HelpLink = "https://github.com/dotnet/roslyn/issues/41640",
    Untestable = "Project-configuration recommendation, not a code-pattern violation; fires based on the absence of the GenerateDocumentationFile MSBuild property and cannot be triggered or suppressed by writing code in the test harness")]
public static class UntestableRules { }
